---
# tasks file for cdp
- name: disable SELINUX
  command: setenforce 0

- name: disable SELINUX on reboot
  selinux:
    state: disabled

- name: disable swappiness
  command: swapoff -a

- name: sysctl swappiness
  sysctl:
    name: vm.swappiness
    value: 1
    reload: yes
    state: present
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf

- name: Installing required packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - vim
    - wget
    - yum-utils
    - ntp
    - telnet
    - unzip
    - nscd

- name: disable firewalld
  systemd:
    state: stopped
    name: firewalld
    enabled: no
    masked: yes

- name: Disable THP
  command: "{{ item }}"
  with_items:
    - echo never > /sys/kernel/mm/transparent_hugepage/enabled
    - echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable THP support scripts added to rc.local
  lineinfile:
    path: /etc/rc.local
    line: |
      echo never > /sys/kernel/mm/transparent_hugepage/enabled
      echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Change permissions of /etc/rc.local to make it run on boot
  shell: chmod +x /etc/rc.d/rc.local
  become_method: sudo

- name: Setting limits.conf - NOFile
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: nofile
    value: 64000
  with_items:
    - soft
    - hard

- name: Setting limits.conf - NProc
  pam_limits:
    domain: '*'
    limit_type: "{{ item }}"
    limit_item: nproc
    value: 64000
  with_items:
    - soft
    - hard

- name: Enable NSCD
  systemd:
    state: started
    enabled: yes
    name: nscd

- name: Removing Chrony
  yum:
    exclude: chrony
    state: present

- name: Starting NTP
  systemd:
    state: started
    enabled: yes
    name: ntpd

- name: Installing OpenJDK-8
  yum:
    name: java-1.8.0-openjdk-devel
    state: present

- name: Create /usr/share/java directory
  file:
    path: /usr/share/java
    state: directory
    mode: 0755

- stat:
    path: /usr/share/java/mysql-connector-java.jar
  register: mysql_connector_java

- name: Download MySQL Connector/J 
  get_url:
    url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.48.zip
    dest: "{{ tmp_dir }}/mysql-connector-java.zip"
    checksum: "md5:5da24facd99964f296ecde32abcd2384"
    mode: 0644
  when: not mysql_connector_java.stat.exists

- name: Extract MySQL Connector/J zip file
  unarchive:
    src: "{{ tmp_dir }}/mysql-connector-java.zip"
    dest: "{{ tmp_dir }}"
    copy: no
  when: not mysql_connector_java.stat.exists

- name: Copy MySQL Connector/J jar file to correct location
  copy:
    src: "{{ tmp_dir }}/mysql-connector-java-5.1.48/mysql-connector-java-5.1.48.jar"
    dest: /usr/share/java/mysql-connector-java.jar
    mode: 0644
    remote_src: yes
  when: not mysql_connector_java.stat.exists

- name: Build hosts file
  lineinfile: dest=/etc/hosts 
              state=present
              dest=/etc/hosts 
              regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}.srv {{ item }}"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"

- name: Add Cloudera Manager Yum Repo
  yum_repository:
    name: Cloudera-Manager
    description: Cloudera YUM repository
    baseurl: https://archive.cloudera.com/cm7/7.0.3/redhat7/yum/
    gpgkey: https://archive.cloudera.com/cm7/7.0.3/redhat7/yum/RPM-GPG-KEY-cloudera
    gpgcheck: yes

- name: Install Cloudera Manager Agents
  yum:
    name:
    - cloudera-manager-daemons
    - cloudera-manager-agent
    update_cache: yes
    state: installed

- name: Configure Cloudera Manager Agent 'server_host'
  lineinfile:
    dest: /etc/cloudera-scm-agent/config.ini
    regexp: "^server_host"
    line: "server_host=master-01.srv"

- name: Restart Cloudera Manager Agents
  service:
    name: cloudera-scm-agent
    state: restarted
    enabled: yes
